from src.pieces.pawn import Pawn
from src.pieces.rook import Rook
from pieces.king import King
from pieces.queen import Queen
from pieces.bishop import Bishop
from pieces.knight import Knight


BASE_PIECES = {
	(0, 6, "w"): Pawn, (0, 7, "w"): Rook,
	(1, 6, "w"): Pawn, (1, 7, "w"): Knight,
	(2, 6, "w"): Pawn, (2, 7, "w"): Bishop,
	(3, 6, "w"): Pawn, (3, 7, "w"): Queen,
	(4, 6, "w"): Pawn, (4, 7, "w"): King,
	(5, 6, "w"): Pawn, (5, 7, "w"): Bishop,
	(6, 6, "w"): Pawn, (6, 7, "w"): Knight,
	(7, 6, "w"): Pawn, (7, 7, "w"): Rook,
	
	(0, 1, "b"): Pawn, (0, 0, "b"): Rook,
	(1, 1, "b"): Pawn, (1, 0, "b"): Knight,
	(2, 1, "b"): Pawn, (2, 0, "b"): Bishop,
	(3, 1, "b"): Pawn, (3, 0, "b"): Queen,
	(4, 1, "b"): Pawn, (4, 0, "b"): King,
	(5, 1, "b"): Pawn, (5, 0, "b"): Bishop,
	(6, 1, "b"): Pawn, (6, 0, "b"): Knight,
	(7, 1, "b"): Pawn, (7, 0, "b"): Rook

}

# SCALING AND FPS
FULL_SCREEN = 0
SCALE = 1
FPS = 10
CELL_W = 50
CELL_H = 50
CELL_SIZE = (CELL_W, CELL_H)
BOARD_W = 8
BOARD_H = 8
BOARD_SIZE = (BOARD_W, BOARD_H)

# DISPLAY INFORMATION
NATIVE_WIDTH = 800
NATIVE_HEIGHT = 600
NATIVE_SIZE = (NATIVE_WIDTH, NATIVE_HEIGHT)
NATIVE_WIDTH_CENTER = NATIVE_WIDTH // 2
NATIVE_HEIGHT_CENTER = NATIVE_HEIGHT // 2
NATIVE_CENTER = (NATIVE_WIDTH_CENTER, NATIVE_HEIGHT_CENTER)
NATIVE_TOP = 0
NATIVE_BOTTOM = NATIVE_HEIGHT
NATIVE_RIGHT = NATIVE_WIDTH
NATIVE_LEFT = 0
NATIVE_TOP_LEFT = (NATIVE_LEFT, NATIVE_TOP)
NATIVE_TOP_CENTER = (NATIVE_WIDTH_CENTER, NATIVE_TOP)
NATIVE_TOP_RIGHT = (NATIVE_WIDTH, NATIVE_TOP)
NATIVE_RIGHT_CENTER = (NATIVE_WIDTH, NATIVE_HEIGHT_CENTER)
NATIVE_BOTTOM_RIGHT = NATIVE_SIZE
NATIVE_BOTTOM_CENTER = (NATIVE_WIDTH_CENTER, NATIVE_HEIGHT)
NATIVE_BOTTOM_LIFT = (NATIVE_LEFT, NATIVE_HEIGHT)
NATIVE_LEFT_CENTER = (NATIVE_LEFT, NATIVE_HEIGHT_CENTER)

DISPLAY_WIDTH = int(NATIVE_WIDTH * SCALE)
DISPLAY_HEIGHT = int(NATIVE_HEIGHT * SCALE)
DISPLAY_SIZE = (DISPLAY_WIDTH, DISPLAY_HEIGHT)
DISPLAY_WIDTH_CENTER = DISPLAY_WIDTH // 2
DISPLAY_HEIGHT_CENTER = DISPLAY_HEIGHT // 2
DISPLAY_CENTER = (DISPLAY_WIDTH_CENTER, DISPLAY_HEIGHT_CENTER)
DISPLAY_TOP = 0
DISPLAY_BOTTOM = DISPLAY_HEIGHT
DISPLAY_RIGHT = DISPLAY_WIDTH
DISPLAY_LEFT = 0
DISPLAY_TOP_LEFT = (DISPLAY_LEFT, DISPLAY_TOP)
DISPLAY_TOP_CENTER = (DISPLAY_WIDTH_CENTER, DISPLAY_TOP)
DISPLAY_TOP_RIGHT = (DISPLAY_WIDTH, DISPLAY_TOP)
DISPLAY_RIGHT_CENTER = (DISPLAY_WIDTH, DISPLAY_HEIGHT_CENTER)
DISPLAY_BOTTOM_RIGHT = DISPLAY_SIZE
DISPLAY_BOTTOM_CENTER = (DISPLAY_WIDTH_CENTER, DISPLAY_HEIGHT)
DISPLAY_BOTTOM_LIFT = (DISPLAY_LEFT, DISPLAY_HEIGHT)
DISPLAY_LEFT_CENTER = (DISPLAY_LEFT, DISPLAY_HEIGHT_CENTER)

# Board position
BOARD_TOP_RIGHT = (
	DISPLAY_WIDTH_CENTER - int(BOARD_W/2 * CELL_W),
	DISPLAY_HEIGHT_CENTER - int(BOARD_H/2 * CELL_H)
)